# https://github.com/lorenwest/node-config
# Config loading order: https://github.com/lorenwest/node-config/wiki/Configuration-Files
app:
  port: 8000
  host: localhost

mongo: mongodb://localhost/pst